sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
env:
  global:
  - COVERAGE: false

matrix:
  fast_finish: true
  include:
  - php: 7.1
    env: MAGENTO_VERSION=2.2.0
  - php: 7.1
    env: MAGENTO_VERSION=2.2.*
  - php: 7.2
    env: MAGENTO_VERSION=2.3.0 CODE_QUALITY=true
  - php: 7.2
    env: MAGENTO_VERSION=2.3.*
  - php: 7.3
    env: MAGENTO_VERSION=2.3.*


language: php

cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.php-cs-fixer"
  - "$HOME/.local"

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - "./Test/script/travis_before_install.sh"

install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > $HOME/.composer/auth.json
  - export MAGENTO_ROOT=`mktemp -d /tmp/mage.XXXXXXXX`
  - "./Test/script/travis_install_magento.sh $MAGENTO_VERSION"

script:
  - "./Test/script/travis_script.sh"
