<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
    <tr class="<?= /* @escapeNotVerified */ $_code ?>" style="width:100%;text-align:right;">
        <td <?= /* @escapeNotVerified */ $block->getLabelProperties() ?>  style="width:88%;text-align:right;">
            <?php if ($_total->getStrong()):?>
            <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else:?>
            <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif?>
        </td>
        <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml($_total->getLabel()) ?>"  style="width:12%;text-align:right;padding-right:20px;">
            <?php if ($_total->getStrong()):?>
            <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?= /* @escapeNotVerified */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
